In [1]:
import numpy as np
import pandas as pd
import rts_data

In [2]:
real_time_load_data = "/home/sam/Research/PowerPhaseRetrieval/data/RTS-GMLC-timeseries/REAL_TIME_regional_Load.csv"
day_ahead_load_data = "/home/sam/Research/PowerPhaseRetrieval/data/RTS-GMLC-timeseries/DAY_AHEAD_regional_Load.csv"
bus_file = "/home/sam/Research/PowerPhaseRetrieval/data/RTS-GMLC-timeseries/bus.csv"
bus_df = pd.read_csv(bus_file)
load_df = pd.read_csv(real_time_load_data)

In [3]:
bus_df[bus_df["Area"]==3]

,Bus ID,Bus Name,BaseKV,Bus Type,MW Load,MVAR Load,V Mag,V Angle,MW Shunt G,MVAR Shunt B,Area,Sub Area,Zone,lat,lng
48,301,Cabell,138.0,PV,108.0,22.0,1.04860,-9.34821,0.0,0.0,3,31.0,31.0,35.047582,-118.821765
49,302,Cabot,138.0,PV,97.0,20.0,1.04864,-9.43100,0.0,0.0,3,31.0,32.0,35.029937,-118.864860
50,303,Caesar,138.0,PQ,180.0,37.0,1.01045,-8.57689,0.0,0.0,3,31.0,31.0,35.217543,-118.043550
51,304,Caine,138.0,PQ,74.0,15.0,1.01785,-12.18784,0.0,0.0,3,31.0,31.0,34.632091,-118.563585
52,305,Calvin,138.0,PQ,71.0,14.0,1.03609,-12.35005,0.0,0.0,3,31.0,31.0,34.873885,-118.510487
53,306,Camus,138.0,PQ,136.0,28.0,1.03260,-14.94205,0.0,-100.0,3,31.0,32.0,34.887168,-118.276200
54,307,Carew,138.0,PV,125.0,25.0,1.03804,-12.54795,0.0,0.0,3,31.0,32.0,34.101266,-118.878178
55,308,Carrel,138.0,PQ,171.0,35.0,1.01056,-15.18287,0.0,0.0,3,31.0,32.0,34.224718,-118.654258
56,309,Carter,138.0,PQ,175.0,36.0,1.02579,-10.44617,0.0,0.0,3,31.0,33.0,34.735758,-118.127342
57,310,Caruso,138.0,PQ,195.0,40.0,1.05000,-12.30117,0.0,0.0,3,31.0,33.0,34.729316,-118.104525
58,311,Cary,230.0,PQ,0.0,0.0,1.02830,-5.74069,0.0,0.0,3,31.0,33.0,34.742094,-118.111933
59,312,Caxton,230.0,PQ,0.0,0.0,1.01900,-4.14604,0.0,0.0,3,31.0,33.0,34.722963,-118.119887
60,313,Cecil,230.0,PV,265.0,54.0,1.03802,-2.41513,0.0,0.0,3,32.0,34.0,34.265268,-118.018855
61,314,Chain,230.0,PV,194.0,39.0,1.04631,-3.20793,0.0,0.0,3,32.0,36.0,34.944964,-117.684879
62,315,Chase,230.0,PV,317.0,64.0,1.04300,7.05088,0.0,0.0,3,32.0,36.0,35.265970,-117.386434
63,316,Chifa,230.0,PV,100.0,20.0,1.04558,6.59875,0.0,0.0,3,32.0,36.0,35.138367,-117.251589
64,317,Chuhsi,230.0,PQ,0.0,0.0,1.04785,10.34418,0.0,0.0,3,32.0,37.0,35.378433,-117.055829
65,318,Clark,230.0,PV,333.0,68.0,1.05000,11.34262,0.0,0.0,3,32.0,37.0,35.505813,-116.976571
66,319,Clay,230.0,PQ,181.0,37.0,1.03953,5.91539,0.0,0.0,3,32.0,35.0,34.917631,-117.124420
67,320,Clive,230.0,PQ,128.0,26.0,1.04389,7.19709,0.0,0.0,3,32.0,35.0,34.462466,-117.063508
68,321,Cobb,230.0,PV,0.0,0.0,1.05000,12.34122,0.0,0.0,3,32.0,37.0,35.745344,-117.115363
69,322,Cole,230.0,PV,0.0,0.0,1.05000,18.06914,0.0,0.0,3,32.0,37.0,36.438958,-117.485272
70,323,Comte,230.0,PV,0.0,0.0,1.05000,8.62112,0.0,0.0,3,32.0,35.0,34.253003,-117.113221
71,324,Curie,230.0,PQ,0.0,0.0,1.01046,1.30606,0.0,0.0,3,32.0,36.0,35.206582,-118.034817
72,325,Curtiss,230.0,PQ,0.0,0.0,1.04986,8.99332,0.0,0.0,3,32.0,35.0,34.251891,-117.128977

In [4]:
load_df

        Year  Month  Day  Period           1            2            3
0       2020      1    1       1  908.277392  1106.417910  1274.834854
1       2020      1    1       2  907.953123  1108.656716  1268.111041
2       2020      1    1       3  906.331778  1110.000000  1263.628500
3       2020      1    1       4  905.358971  1109.104478  1257.801195
4       2020      1    1       5  907.628854  1105.522388  1250.629129
...      ...    ...  ...     ...         ...          ...          ...
105403  2020     12   31     284  989.020366  1206.716418  1334.900912
105404  2020     12   31     285  988.047559  1202.686567  1331.314879
105405  2020     12   31     286  987.723290  1194.179104  1324.591066
105406  2020     12   31     287  987.399022  1187.910448  1313.832966
105407  2020     12   31     288  989.020366  1178.955224  1305.764391

[105408 rows x 7 columns]

In [56]:
def get_rts_load_fractions(bus_df):
    fractions  = pd.DataFrame(columns=["Bus ID","Area","MW Fraction","MVAR Fraction"])
    for area in bus_df["Area"].unique():
        area_load = bus_df[bus_df["Area"]==area]
        area_load["MW Fraction"] = area_load["MW Load"]/area_load["MW Load"].sum()
        area_load["MVAR Fraction"] = area_load["MVAR Load"]/area_load["MVAR Load"].sum()
        fractions = fractions.append(area_load[["Bus ID","Area","MW Fraction","MVAR Fraction"]])
    return fractions

def get_rts_power_factors(bus_df):
    entries = []
    for bus_id in bus_df["Bus ID"]:
        bus_mw = bus_df[bus_df["Bus ID"]==bus_id]["MW Load"].values[0]
        bus_mvar = bus_df[bus_df["Bus ID"]==bus_id]["MVAR Load"].values[0]
        if bus_mw == 0 and bus_mvar == 0:
            bus_pf = 1
        elif bus_mvar == 0:
            bus_pf = 1
        else:
            bus_pf = bus_mw/np.sqrt(bus_mw**2+bus_mvar**2)
        entries.append({"Bus ID":bus_id,"Power Factor":bus_pf})
    return pd.DataFrame(entries,columns=["Bus ID","Power Factor"])

def get_rts_nodal_data_realtime(bus_file=bus_file,real_time_load_data=real_time_load_data):
    # Read in the data
    bus_df = pd.read_csv(bus_file)
    load_df = pd.read_csv(real_time_load_data)
    # Get the bus fractions and power factors
    fractions = get_rts_load_fractions(bus_df)    
    power_factors = get_rts_power_factors(bus_df)
    # Setup nodal dataframes
    nodal_mw_data = pd.DataFrame(columns=bus_df["Bus ID"],index=load_df.index)
    nodal_mvar_data = pd.DataFrame(columns=bus_df["Bus ID"],index=load_df.index)
    # Get the nodal data
    for bus_id in bus_df["Bus ID"]:
        bus_zone = bus_df[bus_df["Bus ID"]==bus_id]["Area"].values[0]
        bus_power_factor = power_factors[power_factors["Bus ID"]==bus_id]["Power Factor"].values[0]
        fraction = fractions[fractions["Bus ID"]==bus_id]["MW Fraction"].values[0]
        nodal_mw_data[bus_id] = fraction*load_df[str(bus_zone)] 
        nodal_mvar_data[bus_id] = nodal_mw_data[bus_id]*np.tan(np.arccos(bus_power_factor))
    return nodal_mw_data,nodal_mvar_data


def get_rts_nodal_data_day_ahead(bus_file=bus_file,day_ahead_load_data=day_ahead_load_data):
    # Read in the data
    bus_df = pd.read_csv(bus_file)
    load_df = pd.read_csv(day_ahead_load_data)
    # Get the bus fractions and power factors
    fractions = get_rts_load_fractions(bus_df)    
    power_factors = get_rts_power_factors(bus_df)
    # Setup nodal dataframes
    nodal_mw_data = pd.DataFrame(columns=bus_df["Bus ID"],index=load_df.index)
    nodal_mvar_data = pd.DataFrame(columns=bus_df["Bus ID"],index=load_df.index)
    # Get the nodal data
    for bus_id in bus_df["Bus ID"]:
        bus_zone = bus_df[bus_df["Bus ID"]==bus_id]["Area"].values[0]
        bus_power_factor = power_factors[power_factors["Bus ID"]==bus_id]["Power Factor"].values[0]
        fraction = fractions[fractions["Bus ID"]==bus_id]["MW Fraction"].values[0]
        nodal_mw_data[bus_id] = fraction*load_df[str(bus_zone)] 
        nodal_mvar_data[bus_id] = nodal_mw_data[bus_id]*np.tan(np.arccos(bus_power_factor))
    return nodal_mw_data,nodal_mvar_data

In [60]:
fractions = get_rts_load_fractions(bus_df)
pfs = get_rts_power_factors(bus_df)
nodal_mw_data,nodal_mvar_data = get_rts_nodal_data_realtime()
nodal_mw_data_day_ahead,nodal_mvar_data_day_ahead = get_rts_nodal_data_day_ahead()

/tmp/ipykernel_75625/2069062057.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  area_load["MW Fraction"] = area_load["MW Load"]/area_load["MW Load"].sum()
/tmp/ipykernel_75625/2069062057.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  area_load["MVAR Fraction"] = area_load["MVAR Load"]/area_load["MVAR Load"].sum()
/tmp/ipykernel_75625/2069062057.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fractions = fractions.append(area_load[["Bus ID","Area","MW Fraction","MVAR Fraction"]])
/tmp/ipykernel_75625/2069062057.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  area_load["MW Fraction"] = area_load["MW Load"]/area_load["MW Load"].sum()
/tmp/ipykernel_75625/2069062057.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  area_load["MVAR Fraction"] = area_load["MVAR Load"]/area_load["MVAR Load"].sum()
/tmp/ipykernel_75625/2069062057.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fractions = fractions.append(area_load[["Bus ID","Area","MW Fraction","MVAR Fraction"]])
/tmp/ipykernel_75625/2069062057.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  area_load["MW Fraction"] = area_load["MW Load"]/area_load["MW Load"].sum()
/tmp/ipykernel_75625/2069062057.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  area_load["MVAR Fraction"] = area_load["MVAR Load"]/area_load["MVAR Load"].sum()
/tmp/ipykernel_75625/2069062057.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fractions = fractions.append(area_load[["Bus ID","Area","MW Fraction","MVAR Fraction"]])
/tmp/ipykernel_75625/2069062057.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  area_load["MW Fraction"] = area_load["MW Load"]/area_load["MW Load"].sum()
/tmp/ipykernel_75625/2069062057.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  area_load["MVAR Fraction"] = area_load["MVAR Load"]/area_load["MVAR Load"].sum()
/tmp/ipykernel_75625/2069062057.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fractions = fractions.append(area_load[["Bus ID","Area","MW Fraction","MVAR Fraction"]])
/tmp/ipykernel_75625/2069062057.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  area_load["MW Fraction"] = area_load["MW Load"]/area_load["MW Load"].sum()
/tmp/ipykernel_75625/2069062057.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  area_load["MVAR Fraction"] = area_load["MVAR Load"]/area_load["MVAR Load"].sum()
/tmp/ipykernel_75625/2069062057.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fractions = fractions.append(area_load[["Bus ID","Area","MW Fraction","MVAR Fraction"]])
/tmp/ipykernel_75625/2069062057.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  area_load["MW Fraction"] = area_load["MW Load"]/area_load["MW Load"].sum()
/tmp/ipykernel_75625/2069062057.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  area_load["MVAR Fraction"] = area_load["MVAR Load"]/area_load["MVAR Load"].sum()
/tmp/ipykernel_75625/2069062057.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fractions = fractions.append(area_load[["Bus ID","Area","MW Fraction","MVAR Fraction"]])
/tmp/ipykernel_75625/2069062057.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  area_load["MW Fraction"] = area_load["MW Load"]/area_load["MW Load"].sum()
/tmp/ipykernel_75625/2069062057.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  area_load["MVAR Fraction"] = area_load["MVAR Load"]/area_load["MVAR Load"].sum()
/tmp/ipykernel_75625/2069062057.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fractions = fractions.append(area_load[["Bus ID","Area","MW Fraction","MVAR Fraction"]])
/tmp/ipykernel_75625/2069062057.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  area_load["MW Fraction"] = area_load["MW Load"]/area_load["MW Load"].sum()
/tmp/ipykernel_75625/2069062057.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  area_load["MVAR Fraction"] = area_load["MVAR Load"]/area_load["MVAR Load"].sum()
/tmp/ipykernel_75625/2069062057.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fractions = fractions.append(area_load[["Bus ID","Area","MW Fraction","MVAR Fraction"]])
/tmp/ipykernel_75625/2069062057.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  area_load["MW Fraction"] = area_load["MW Load"]/area_load["MW Load"].sum()
/tmp/ipykernel_75625/2069062057.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  area_load["MVAR Fraction"] = area_load["MVAR Load"]/area_load["MVAR Load"].sum()
/tmp/ipykernel_75625/2069062057.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fractions = fractions.append(area_load[["Bus ID","Area","MW Fraction","MVAR Fraction"]])

In [62]:
nodal_mw_data.to_csv("/home/sam/Research/PowerPhaseRetrieval/data/RTS-GMLC-timeseries/nodal-realtime/nodal_mw_data.csv")
nodal_mvar_data.to_csv("/home/sam/Research/PowerPhaseRetrieval/data/RTS-GMLC-timeseries/nodal-realtime/nodal_mvar_data.csv")

In [64]:
nodal_mw_data_day_ahead.to_csv("/home/sam/Research/PowerPhaseRetrieval/data/RTS-GMLC-timeseries/nodal-dayahead/nodal_mw_data.csv")
nodal_mvar_data_day_ahead.to_csv("/home/sam/Research/PowerPhaseRetrieval/data/RTS-GMLC-timeseries/nodal-dayahead/nodal_mvar_data.csv")

In [54]:
fractions[fractions["Bus ID"]==bus_id]["MW Fraction"]

0    0.037895
Name: MW Fraction, dtype: object

In [67]:
nodal_mw_data_day_ahead

Bus ID,101,102,103,104,105,106,107,108,109,110,...,316,317,318,319,320,321,322,323,324,325
0,37.327066,33.525235,62.211776,25.575952,24.539090,47.004453,43.202622,59.101188,60.483671,67.396091,...,43.846884,0.0,146.010123,79.362860,56.124011,0.0,0.0,0.0,0.0,0.0
1,37.353785,33.549233,62.256309,25.594260,24.556655,47.038100,43.233548,59.143493,60.526967,67.444334,...,41.838026,0.0,139.320626,75.726827,53.552673,0.0,0.0,0.0,0.0,0.0
2,37.954973,34.089189,63.258288,26.006185,24.951880,47.795151,43.929367,60.095374,61.501113,68.529812,...,40.904777,0.0,136.212907,74.037646,52.358115,0.0,0.0,0.0,0.0,0.0
3,39.264226,35.265092,65.440376,26.903266,25.812593,49.443840,45.444706,62.168357,63.622588,70.893741,...,40.351155,0.0,134.369345,73.035590,51.649478,0.0,0.0,0.0,0.0,0.0
4,43.191984,38.792801,71.986640,29.594508,28.394730,54.389906,49.990722,68.387308,69.987011,77.985527,...,40.841506,0.0,136.002215,73.923126,52.277128,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,51.889164,46.604156,86.481940,35.553686,34.112321,65.341910,60.056903,82.157843,84.079664,93.688768,...,60.139196,0.0,200.263524,108.851946,76.978171,0.0,0.0,0.0,0.0,0.0
8780,50.312716,45.188273,83.854527,34.473528,33.075953,63.356754,58.232311,79.661801,81.525235,90.842405,...,58.984499,0.0,196.418380,106.761942,75.500158,0.0,0.0,0.0,0.0,0.0
8781,47.052944,42.260515,78.421573,32.239980,30.932954,59.251855,54.459426,74.500495,76.243196,84.956705,...,56.121481,0.0,186.884530,101.579880,71.835495,0.0,0.0,0.0,0.0,0.0
8782,43.178624,38.780802,71.964374,29.585354,28.385948,54.373083,49.975260,68.366155,69.965364,77.961405,...,51.692502,0.0,172.136033,93.563429,66.166403,0.0,0.0,0.0,0.0,0.0
8783,40.960910,36.788966,68.268184,28.065809,26.928006,51.580406,47.408461,64.854775,66.371846,73.957199,...,47.643151,0.0,158.651693,86.234103,60.983233,0.0,0.0,0.0,0.0,0.0

In [15]:
pfs

    Bus ID  Power Factor
0      101      0.979877
1      102      0.979398
2      103      0.979520
3      104      0.980068
4      105      0.981109
..     ...           ...
68     321      1.000000
69     322      1.000000
70     323      1.000000
71     324      1.000000
72     325      1.000000

[73 rows x 2 columns]